- readme.md
> Add learning materials for Agile

- readme.md
> Added more software testing books with download links

- .github/workdflows/mdlinkcheck.yml
- .github/workdflows/mlc_config.json
> added github actions for md link checks

- readme.md
> added learning material and tools for ar, vr apps testing

- .github/FUNDING.yml
> added funding.yml

- readme.md
> updated free learning resources for git

- readme.md
> added ivr testing learning resources

- readme.md
> added resources for learning github actions

- readme.md
> Add free learning resources for BDD

- .gitignore
- readme.md
> added blog link - "Beginners guide to Appium 2.0"

- readme.md
> Added learning resources for gRPC

- readme.md
> added free learning resources for DB and DB Testing

- readme.md
> Added link to install android studio on Windows 10 and removed the fake blog link to flutter test automation blog

- readme.md
> added section for coding principles learning materials

- readme.md
> added flutter tutorial blog link

- readme.md
> added selenium manager blog link

- readme.md
> added contract testing tutorial links

- readme.md
> added jenkins 21+ practical guides link

- readme.md
> added links to APISec University courses in Security Testing section

- readme.md
> updated readme for git tutorial websites

- readme.md
> added playwright learning links

- readme.md
> added docker cheat sheet links, updated docker official youtube channel link

- readme.md
> removed pdfdrive link

- readme.md
> added new section of test automation frameworks

- readme.md
> added qa assistance section

- readme.md
> added mobile testing material links

- readme.md
> added qa assistance tools

- readme.md
> added live projects links

- readme.md
> added demo websites for practicing web automation

- readme.md
> added demo web automation practice links

- readme.md
> added blogs, tutorial links and video links related to selenium and software testing

- readme.md
> updated flutter automation blog link

- readme.md
> added new section for maven in QA assistance

- readme.md
> added Junit tutorials section

- readme.md
> added testng tutorials section

- readme.md
> corrected the name to Testng and added new jenkins tutorial links

- readme.md
> added link to scandium test drive webinar

- readme.md
> added link to practical guide to mobile testing and handling alert and popup in appium

- readme.md
> added burp suite tutorial links

- readme.md
> updated API security testing links and added more software testing youtube channel links

- readme.md
> updated latest playwright tutorial blog link: working with dropdowns

- readme.md
> added youtube video tutorial link for locator strategies video

- readme.md
> Added Nodemaven in the tools section and updated all links

- readme.md
> added new tutorial/blog links to different sections

- readme.md
> added new section for accessibility testing learning materials

- readme.md
> Add roadmap for Data Structures and Algorithms

- readme.md
Added latests blogs links related to Selenium WebDriver, WebdriverIO, Playwright.
Added new section for Selenium Grid 4 blogs.
> Added latest blogs and tutorials link

- readme.md
Added Mockium, a free online data generator (no limitation on the number of records generated), to "QA Assistance / Tools"
> Add mockium to QA Assistance / Tools

- readme.md
> updated awesome github repo links

- readme.md
> added a new section for ISTQB learning materials

- readme.md
> added software design learning material links

- readme.md
> Added demo link of restful ecommerce for api testing practice

- readme.md
> Added Playwright Tutorial blog links for web and api automation, added discord server link.

- readme.md
> added links to Selenium and Appium blogs published on LambdaTest Website

- readme.md
> added Ultra reporter in QA tools section

- readme.md
> added links to playwright patch and delete api testing blogs

- readme.md
> updated demo mobile apps

- readme.md
> added free security testing courses link in security testing section

- readme.md
added links to typescript course, added course links for python, js, java, added few more testing blog links
Closes #180
> New links updated

- readme.md
> added free QA tool links

- readme.md
> added new section for ai/ml learning materials

- readme.md
> added learning materials, courses and youtube channels for devops

- readme.md
- Added roadmap links
- Added learning materials for python, 
- Added AI and ML courses
- Demo api and websites for practicing automation testing
Closes #185 
closes #186
> Updated Readme with more learning materials and roadmaps

- readme.md
- Removed Broken links
- Added new links for the following: 
- Graphql API Testing learning materials
- Software testing github repos
- Playwright custom logger blog
- Contract testing tutorials
> removed broken links and updated learning materials

- readme.md
Add jsoning (my website), an open source mock REST API,  to Demo APIs for Practice
> Add jsoning to Demo APIs for Practice

- readme.md
added learning materials for api, web testing using pytest, added other section for pytest for learning pytest in deep
closes #188
> Added pytest learning materials

- readme.md
> updated all javatpoint links to tpointtech

- readme.md
> added links for software testing tutorials and real python website

- readme.md
> Added GitLab tutorials

- readme.md
> added python, Java, Software Testing and AI learning maetrials

- readme.md
added Keploy.io in ai tools for automation. Keploy is a tool used for automated api and unit testing. Keploy has a vs code extension that can be used for single click automated test generation and a unit test pr agent that generates unit tests after each change and pr using diff algorithms
> added keploy for api testing

- readme.md
> added links to software testing, jenkins tutorial and devops

- readme.md
> removed broken links, added links for databases and devops

- readme.md
> added links to free programming and devops books

- readme.md
> added devops learning materials

- readme.md
- Software testing materials added 
- Moved all software testing blogs from tutorials to blog section
- Closes #217
> updated readme 

- readme.md
- added DevOps exercises link 
- moved some links to correct places in readme
> Readme updated with more learning materials

- readme.md
> added python and devops learning materials

- readme.md
> Fixed Broken links and removed dead links

- readme.md
> Added qa interview prep section

- readme.md
> added links for learning linux

- readme.md
> added links for terrraform tutorials

- readme.md
> added devops learning material links

- readme.md
> added playwright tutorial links

- readme.md
> added learning materials for cicd security and cybersecurity

- readme.md
> added AI/ML learning links

- readme.md
> Updated Java System design and removed dead link from read

- readme.md
> updated pdf drive links for SOftware Testing pdfs

- readme.md
Add a playbook about test case design
> Add a playbook about test case design

- readme.md
> added tools frameworks for api testing
